export type APIFailureAction =
'API_TALKS_POST_FAILURE' |
'API_TALKS_PATCH_FAILURE' |
'API_TALKS_GET_FAILURE' |
'API_TALKS_DELETE_FAILURE' |
'API_LOGIN_USER_FAILURE' |
'API_REGISTER_USER_FAILURE' |
'API_TALKS_LIST_FAILURE' |
'API_VOTE_POST_FAILURE'

export type APIResetAction =
'API_LOGIN_USER_RESET' |
'API_REGISTER_USER_RESET' |
'API_TALKS_DELETE_RESET' |
'API_TALKS_GET_RESET' |
'API_TALKS_LIST_RESET' |
'API_TALKS_PATCH_RESET' |
'API_TALKS_POST_RESET' |
'API_VOTE_POST_RESET'

export type APIStartedAction =
'API_TALKS_POST_STARTED' |
'API_TALKS_PATCH_STARTED' |
'API_TALKS_GET_STARTED' |
'API_TALKS_DELETE_STARTED' |
'API_LOGIN_USER_STARTED' |
'API_REGISTER_USER_STARTED' |
'API_TALKS_LIST_STARTED' |
'API_VOTE_POST_STARTED'


export type APISuccessAction =
'API_TALKS_POST_SUCCESS' |
'API_TALKS_PATCH_SUCCESS' |
'API_TALKS_GET_SUCCESS' |
'API_TALKS_DELETE_SUCCESS' |
'API_LOGIN_USER_SUCCESS' |
'API_REGISTER_USER_SUCCESS' |
'API_TALKS_LIST_SUCCESS' |
'API_VOTE_POST_SUCCESS'

export type APIReducerParameters = [
    APIStartedAction, |
    APISuccessAction, |
    APIFailureAction, |
    APIResetAction,
]
