#!/usr/bin/env bash

set -e

if ! [ -x "$(command -v docker)" ]; then
    echo "Docker is not installed. Please install docker and try again." >&2
    exit 1
fi

if ! [ -x "$(command -v docker-compose)" ]; then
    echo "Docker Compose is not installed. Please install docker-compose and try again." >&2
    exit 1
fi

