#!/usr/bin/env bash

set -e

echo "
test-fullstack NestJS/React CLI
"

if [ -z "$1" ]; then
    echo "Starting test-fullstack development stack..."
    docker-compose up
elif [ "$1" == "test" ]; then
    echo "Starting Backend tests..."
    bash -c "docker-compose run --rm api yarn test"
    echo "Starting Frontend tests..."
    bash -c "docker-compose run --rm frontend yarn test"
else
    docker-compose "$@"
fi
