export const FETCH_TALKS = 'FETCH_TALKS'
export const FETCH_TALKS_SUCCESS = 'FETCH_TALKS_SUCCESS'
export const FETCH_TALKS_FAIL = 'FETCH_TALKS_FAIL'

export const UPVOTE_TALK = 'UPVOTE_TALK'
export const UPVOTE_TALK_SUCCESS = 'UPVOTE_TALK_SUCCESS'
export const UPVOTE_TALK_FAIL = 'UPVOTE_TALK_FAIL'

export const CREATE_TALK = 'CREATE_TALK'
export const CREATE_TALK_SUCCESS = 'CREATE_TALK_SUCCESS'
export const CREATE_TALK_FAIL = 'CREATE_TALK_FAIL'
